name: Create Release (tags only)

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Resolve notes file path
        id: notes
        run: |
          NOTES="RELEASE_NOTES.md"
          if [ ! -f "$NOTES" ]; then
            echo "::error file=$NOTES::No existe el fichero de release notes"
            exit 1
          fi
          echo "file=$NOTES" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          # Marca prerelease si el tag contiene sufijos comunes
          prerelease: ${{ contains(github.ref_name, '-rc') || contains(github.ref_name, '-beta') || contains(github.ref_name, '-alpha') }}
          body_path: ${{ steps.notes.outputs.file }}
          files: |
            dist/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
